language: java
jdk: openjdk8
install: echo "Over-riding default script for travis-ci"
dist: trusty
script:
  - jdk_switcher use openjdk8
  - mvn clean package -q
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - "$HOME/.m2"
notifications:
   slack: sunbird-ci:UegIg4Bf86V3HcXAB2uXNLGI
   on_success: never
   on_failure: always
   email:
     recipients:
      - manzarul.haque@tarento.com
      - amit.kumar@tarento.com
      - vinayab@ilimi.in
     on_success: never
     on_failure: always
