// ============================================================================
//
// Copyright (c) 2006-2015, Talend Inc.
//
// This source code has been automatically generated by_Talend Open Studio for Big Data
// / Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package userexternalidmigration.usermigrationupdatechannel_0_1;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;
import routines.StringHandling;
import routines.TalendString;
import routines.system.*;
import routines.system.api.*;

@SuppressWarnings("unused")

/**
 * Job: UserMigrationUpdateChannel Purpose: UserMigrationUpdateChannel<br>
 * Description: UserMigrationUpdateChannel <br>
 *
 * @author user@talend.com
 * @version 7.0.1.20180411_1414
 * @status DEV
 */
public class UserMigrationUpdateChannel implements TalendJob {

  protected static void logIgnoredError(String message, Throwable cause) {
    System.err.println(message);
    if (cause != null) {
      cause.printStackTrace();
    }
  }

  public final Object obj = new Object();

  // for transmiting parameters purpose
  private Object valueObject = null;

  public Object getValueObject() {
    return this.valueObject;
  }

  public void setValueObject(Object valueObject) {
    this.valueObject = valueObject;
  }

  private static final String defaultCharset = java.nio.charset.Charset.defaultCharset().name();

  private static final String utf8Charset = "UTF-8";
  // contains type for every context property
  public class PropertiesWithType extends java.util.Properties {
    private static final long serialVersionUID = 1L;
    private java.util.Map<String, String> propertyTypes = new java.util.HashMap<>();

    public PropertiesWithType(java.util.Properties properties) {
      super(properties);
    }

    public PropertiesWithType() {
      super();
    }

    public void setContextType(String key, String type) {
      propertyTypes.put(key, type);
    }

    public String getContextType(String key) {
      return propertyTypes.get(key);
    }
  }

  // create and load default properties
  private java.util.Properties defaultProps = new java.util.Properties();
  // create application properties with default
  public class ContextProperties extends PropertiesWithType {

    private static final long serialVersionUID = 1L;

    public ContextProperties(java.util.Properties properties) {
      super(properties);
    }

    public ContextProperties() {
      super();
    }

    public void synchronizeContext() {

      if (sunbird_cassandra_keyspace != null) {

        this.setProperty("sunbird_cassandra_keyspace", sunbird_cassandra_keyspace.toString());
      }

      if (sunbird_cassandra_password != null) {

        this.setProperty("sunbird_cassandra_password", sunbird_cassandra_password.toString());
      }

      if (sunbird_cassandra_port != null) {

        this.setProperty("sunbird_cassandra_port", sunbird_cassandra_port.toString());
      }

      if (sunbird_cassandra_server != null) {

        this.setProperty("sunbird_cassandra_server", sunbird_cassandra_server.toString());
      }

      if (sunbird_cassandra_username != null) {

        this.setProperty("sunbird_cassandra_username", sunbird_cassandra_username.toString());
      }

      if (sunbird_channel_migration_log_file != null) {

        this.setProperty(
            "sunbird_channel_migration_log_file", sunbird_channel_migration_log_file.toString());
      }
    }

    public String sunbird_cassandra_keyspace;

    public String getSunbird_cassandra_keyspace() {
      return this.sunbird_cassandra_keyspace;
    }

    public java.lang.String sunbird_cassandra_password;

    public java.lang.String getSunbird_cassandra_password() {
      return this.sunbird_cassandra_password;
    }

    public String sunbird_cassandra_port;

    public String getSunbird_cassandra_port() {
      return this.sunbird_cassandra_port;
    }

    public String sunbird_cassandra_server;

    public String getSunbird_cassandra_server() {
      return this.sunbird_cassandra_server;
    }

    public String sunbird_cassandra_username;

    public String getSunbird_cassandra_username() {
      return this.sunbird_cassandra_username;
    }

    public String sunbird_channel_migration_log_file;

    public String getSunbird_channel_migration_log_file() {
      return this.sunbird_channel_migration_log_file;
    }
  }

  private ContextProperties context = new ContextProperties();

  public ContextProperties getContext() {
    return this.context;
  }

  private final String jobVersion = "0.1";
  private final String jobName = "UserMigrationUpdateChannel";
  private final String projectName = "USEREXTERNALIDMIGRATION";
  public Integer errorCode = null;
  private String currentComponent = "";

  private final java.util.Map<String, Object> globalMap = new java.util.HashMap<String, Object>();
  private static final java.util.Map<String, Object> junitGlobalMap =
      new java.util.HashMap<String, Object>();

  private final java.util.Map<String, Long> start_Hash = new java.util.HashMap<String, Long>();
  private final java.util.Map<String, Long> end_Hash = new java.util.HashMap<String, Long>();
  private final java.util.Map<String, Boolean> ok_Hash = new java.util.HashMap<String, Boolean>();
  public final java.util.List<String[]> globalBuffer = new java.util.ArrayList<String[]>();

  private RunStat runStat = new RunStat();

  // OSGi DataSource
  private static final String KEY_DB_DATASOURCES = "KEY_DB_DATASOURCES";

  private static final String KEY_DB_DATASOURCES_RAW = "KEY_DB_DATASOURCES_RAW";

  public void setDataSources(java.util.Map<String, javax.sql.DataSource> dataSources) {
    java.util.Map<String, routines.system.TalendDataSource> talendDataSources =
        new java.util.HashMap<String, routines.system.TalendDataSource>();
    for (java.util.Map.Entry<String, javax.sql.DataSource> dataSourceEntry :
        dataSources.entrySet()) {
      talendDataSources.put(
          dataSourceEntry.getKey(),
          new routines.system.TalendDataSource(dataSourceEntry.getValue()));
    }
    globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
    globalMap.put(
        KEY_DB_DATASOURCES_RAW, new java.util.HashMap<String, javax.sql.DataSource>(dataSources));
  }

  private final java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
  private final java.io.PrintStream errorMessagePS =
      new java.io.PrintStream(new java.io.BufferedOutputStream(baos));

  public String getExceptionStackTrace() {
    if ("failure".equals(this.getStatus())) {
      errorMessagePS.flush();
      return baos.toString();
    }
    return null;
  }

  private Exception exception;

  public Exception getException() {
    if ("failure".equals(this.getStatus())) {
      return this.exception;
    }
    return null;
  }

  private class TalendException extends Exception {

    private static final long serialVersionUID = 1L;

    private java.util.Map<String, Object> globalMap = null;
    private Exception e = null;
    private String currentComponent = null;
    private String virtualComponentName = null;

    public void setVirtualComponentName(String virtualComponentName) {
      this.virtualComponentName = virtualComponentName;
    }

    private TalendException(
        Exception e, String errorComponent, final java.util.Map<String, Object> globalMap) {
      this.currentComponent = errorComponent;
      this.globalMap = globalMap;
      this.e = e;
    }

    public Exception getException() {
      return this.e;
    }

    public String getCurrentComponent() {
      return this.currentComponent;
    }

    public String getExceptionCauseMessage(Exception e) {
      Throwable cause = e;
      String message = null;
      int i = 10;
      while (null != cause && 0 < i--) {
        message = cause.getMessage();
        if (null == message) {
          cause = cause.getCause();
        } else {
          break;
        }
      }
      if (null == message) {
        message = e.getClass().getName();
      }
      return message;
    }

    @Override
    public void printStackTrace() {
      if (!(e instanceof TalendException || e instanceof TDieException)) {
        if (virtualComponentName != null
            && currentComponent.indexOf(virtualComponentName + "_") == 0) {
          globalMap.put(virtualComponentName + "_ERROR_MESSAGE", getExceptionCauseMessage(e));
        }
        globalMap.put(currentComponent + "_ERROR_MESSAGE", getExceptionCauseMessage(e));
        System.err.println("Exception in component " + currentComponent + " (" + jobName + ")");
      }
      if (!(e instanceof TDieException)) {
        if (e instanceof TalendException) {
          e.printStackTrace();
        } else {
          e.printStackTrace();
          e.printStackTrace(errorMessagePS);
          UserMigrationUpdateChannel.this.exception = e;
        }
      }
      if (!(e instanceof TalendException)) {
        try {
          for (java.lang.reflect.Method m : this.getClass().getEnclosingClass().getMethods()) {
            if (m.getName().compareTo(currentComponent + "_error") == 0) {
              m.invoke(
                  UserMigrationUpdateChannel.this, new Object[] {e, currentComponent, globalMap});
              break;
            }
          }

          if (!(e instanceof TDieException)) {}
        } catch (Exception e) {
          this.e.printStackTrace();
        }
      }
    }
  }

  public void tCassandraConnection_1_error(
      Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap)
      throws TalendException {

    end_Hash.put(errorComponent, System.currentTimeMillis());

    status = "failure";

    tCassandraConnection_1_onSubJobError(exception, errorComponent, globalMap);
  }

  public void tCassandraInput_1_error(
      Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap)
      throws TalendException {

    end_Hash.put(errorComponent, System.currentTimeMillis());

    status = "failure";

    tCassandraInput_1_onSubJobError(exception, errorComponent, globalMap);
  }

  public void tMap_1_error(
      Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap)
      throws TalendException {

    end_Hash.put(errorComponent, System.currentTimeMillis());

    status = "failure";

    tCassandraInput_1_onSubJobError(exception, errorComponent, globalMap);
  }

  public void tFileOutputDelimited_1_error(
      Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap)
      throws TalendException {

    end_Hash.put(errorComponent, System.currentTimeMillis());

    status = "failure";

    tCassandraInput_1_onSubJobError(exception, errorComponent, globalMap);
  }

  public void tCassandraOutput_1_error(
      Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap)
      throws TalendException {

    end_Hash.put(errorComponent, System.currentTimeMillis());

    status = "failure";

    tCassandraInput_1_onSubJobError(exception, errorComponent, globalMap);
  }

  public void tCassandraClose_1_error(
      Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap)
      throws TalendException {

    end_Hash.put(errorComponent, System.currentTimeMillis());

    status = "failure";

    tCassandraClose_1_onSubJobError(exception, errorComponent, globalMap);
  }

  public void tCassandraInput_2_error(
      Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap)
      throws TalendException {

    end_Hash.put(errorComponent, System.currentTimeMillis());

    status = "failure";

    tCassandraInput_2_onSubJobError(exception, errorComponent, globalMap);
  }

  public void tAdvancedHash_row2_error(
      Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap)
      throws TalendException {

    end_Hash.put(errorComponent, System.currentTimeMillis());

    status = "failure";

    tCassandraInput_2_onSubJobError(exception, errorComponent, globalMap);
  }

  public void tCassandraConnection_1_onSubJobError(
      Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap)
      throws TalendException {

    resumeUtil.addLog(
        "SYSTEM_LOG",
        "NODE:" + errorComponent,
        "",
        Thread.currentThread().getId() + "",
        "FATAL",
        "",
        exception.getMessage(),
        ResumeUtil.getExceptionStackTrace(exception),
        "");
  }

  public void tCassandraInput_1_onSubJobError(
      Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap)
      throws TalendException {

    resumeUtil.addLog(
        "SYSTEM_LOG",
        "NODE:" + errorComponent,
        "",
        Thread.currentThread().getId() + "",
        "FATAL",
        "",
        exception.getMessage(),
        ResumeUtil.getExceptionStackTrace(exception),
        "");
  }

  public void tCassandraClose_1_onSubJobError(
      Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap)
      throws TalendException {

    resumeUtil.addLog(
        "SYSTEM_LOG",
        "NODE:" + errorComponent,
        "",
        Thread.currentThread().getId() + "",
        "FATAL",
        "",
        exception.getMessage(),
        ResumeUtil.getExceptionStackTrace(exception),
        "");
  }

  public void tCassandraInput_2_onSubJobError(
      Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap)
      throws TalendException {

    resumeUtil.addLog(
        "SYSTEM_LOG",
        "NODE:" + errorComponent,
        "",
        Thread.currentThread().getId() + "",
        "FATAL",
        "",
        exception.getMessage(),
        ResumeUtil.getExceptionStackTrace(exception),
        "");
  }

  public void tCassandraConnection_1Process(final java.util.Map<String, Object> globalMap)
      throws TalendException {
    globalMap.put("tCassandraConnection_1_SUBPROCESS_STATE", 0);

    final boolean execStat = this.execStat;

    String iterateId = "";

    String currentComponent = "";
    java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

    try {
      // TDI-39566 avoid throwing an useless Exception
      boolean resumeIt = true;
      if (globalResumeTicket == false && resumeEntryMethodName != null) {
        String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
        resumeIt = resumeEntryMethodName.equals(currentMethodName);
      }
      if (resumeIt || globalResumeTicket) { // start the resume
        globalResumeTicket = true;

        /** [tCassandraConnection_1 begin ] start */
        ok_Hash.put("tCassandraConnection_1", false);
        start_Hash.put("tCassandraConnection_1", System.currentTimeMillis());

        currentComponent = "tCassandraConnection_1";

        int tos_count_tCassandraConnection_1 = 0;

        class BytesLimit65535_tCassandraConnection_1 {
          public void limitLog4jByte() throws Exception {}
        }

        new BytesLimit65535_tCassandraConnection_1().limitLog4jByte();

        /** [tCassandraConnection_1 begin ] stop */

        /** [tCassandraConnection_1 main ] start */
        currentComponent = "tCassandraConnection_1";

        com.datastax.driver.core.Cluster cluster_tCassandraConnection_1 =
            com.datastax.driver.core.Cluster.builder()
                .addContactPoints(context.sunbird_cassandra_server.split(","))
                .withPort(Integer.valueOf(context.sunbird_cassandra_port))
                .withCredentials(
                    context.sunbird_cassandra_username, context.sunbird_cassandra_password)
                .build();

        com.datastax.driver.core.Session connection_tCassandraConnection_1 = null;
        connection_tCassandraConnection_1 = cluster_tCassandraConnection_1.connect();
        globalMap.put("cluster_tCassandraConnection_1", cluster_tCassandraConnection_1);
        globalMap.put("connection_tCassandraConnection_1", connection_tCassandraConnection_1);

        tos_count_tCassandraConnection_1++;

        /** [tCassandraConnection_1 main ] stop */

        /** [tCassandraConnection_1 process_data_begin ] start */
        currentComponent = "tCassandraConnection_1";

        /** [tCassandraConnection_1 process_data_begin ] stop */

        /** [tCassandraConnection_1 process_data_end ] start */
        currentComponent = "tCassandraConnection_1";

        /** [tCassandraConnection_1 process_data_end ] stop */

        /** [tCassandraConnection_1 end ] start */
        currentComponent = "tCassandraConnection_1";

        ok_Hash.put("tCassandraConnection_1", true);
        end_Hash.put("tCassandraConnection_1", System.currentTimeMillis());

        if (execStat) {
          runStat.updateStatOnConnection("OnComponentOk1", 0, "ok");
        }
        tCassandraInput_1Process(globalMap);

        /** [tCassandraConnection_1 end ] stop */
      } // end the resume

    } catch (java.lang.Exception e) {

      TalendException te = new TalendException(e, currentComponent, globalMap);

      throw te;
    } catch (java.lang.Error error) {

      runStat.stopThreadStat();

      throw error;
    } finally {

      try {

        /** [tCassandraConnection_1 finally ] start */
        currentComponent = "tCassandraConnection_1";

        /** [tCassandraConnection_1 finally ] stop */
      } catch (java.lang.Exception e) {
        // ignore
      } catch (java.lang.Error error) {
        // ignore
      }
      resourceMap = null;
    }

    globalMap.put("tCassandraConnection_1_SUBPROCESS_STATE", 1);
  }

  public static class toLogStruct implements routines.system.IPersistableRow<toLogStruct> {
    static final byte[] commonByteArrayLock_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel =
        new byte[0];
    static byte[] commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel = new byte[0];
    protected static final int DEFAULT_HASHCODE = 1;
    protected static final int PRIME = 31;
    protected int hashCode = DEFAULT_HASHCODE;
    public boolean hashCodeDirty = true;

    public String loopKey;

    public String UserId;

    public String getUserId() {
      return this.UserId;
    }

    public String NewChannel;

    public String getNewChannel() {
      return this.NewChannel;
    }

    public String OldChannel;

    public String getOldChannel() {
      return this.OldChannel;
    }

    @Override
    public int hashCode() {
      if (this.hashCodeDirty) {
        final int prime = PRIME;
        int result = DEFAULT_HASHCODE;

        result = prime * result + ((this.UserId == null) ? 0 : this.UserId.hashCode());

        this.hashCode = result;
        this.hashCodeDirty = false;
      }
      return this.hashCode;
    }

    @Override
    public boolean equals(Object obj) {
      if (this == obj) return true;
      if (obj == null) return false;
      if (getClass() != obj.getClass()) return false;
      final toLogStruct other = (toLogStruct) obj;

      if (this.UserId == null) {
        if (other.UserId != null) return false;

      } else if (!this.UserId.equals(other.UserId)) return false;

      return true;
    }

    public void copyDataTo(toLogStruct other) {

      other.UserId = this.UserId;
      other.NewChannel = this.NewChannel;
      other.OldChannel = this.OldChannel;
    }

    public void copyKeysDataTo(toLogStruct other) {

      other.UserId = this.UserId;
    }

    private String readString(ObjectInputStream dis) throws IOException {
      String strReturn = null;
      int length = 0;
      length = dis.readInt();
      if (length == -1) {
        strReturn = null;
      } else {
        if (length > commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel.length) {
          if (length < 1024
              && commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel.length == 0) {
            commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel = new byte[1024];
          } else {
            commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel =
                new byte[2 * length];
          }
        }
        dis.readFully(
            commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel, 0, length);
        strReturn =
            new String(
                commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel,
                0,
                length,
                utf8Charset);
      }
      return strReturn;
    }

    private void writeString(String str, ObjectOutputStream dos) throws IOException {
      if (str == null) {
        dos.writeInt(-1);
      } else {
        byte[] byteArray = str.getBytes(utf8Charset);
        dos.writeInt(byteArray.length);
        dos.write(byteArray);
      }
    }

    public void readData(ObjectInputStream dis) {

      synchronized (commonByteArrayLock_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel) {
        try {

          int length = 0;

          this.UserId = readString(dis);

          this.NewChannel = readString(dis);

          this.OldChannel = readString(dis);

        } catch (IOException e) {
          throw new RuntimeException(e);
        }
      }
    }

    public void writeData(ObjectOutputStream dos) {
      try {

        // String

        writeString(this.UserId, dos);

        // String

        writeString(this.NewChannel, dos);

        // String

        writeString(this.OldChannel, dos);

      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    }

    public String toString() {

      StringBuilder sb = new StringBuilder();
      sb.append(super.toString());
      sb.append("[");
      sb.append("UserId=" + UserId);
      sb.append(",NewChannel=" + NewChannel);
      sb.append(",OldChannel=" + OldChannel);
      sb.append("]");

      return sb.toString();
    }

    /** Compare keys */
    public int compareTo(toLogStruct other) {

      int returnValue = -1;

      returnValue = checkNullsAndCompare(this.UserId, other.UserId);
      if (returnValue != 0) {
        return returnValue;
      }

      return returnValue;
    }

    private int checkNullsAndCompare(Object object1, Object object2) {
      int returnValue = 0;
      if (object1 instanceof Comparable && object2 instanceof Comparable) {
        returnValue = ((Comparable) object1).compareTo(object2);
      } else if (object1 != null && object2 != null) {
        returnValue = compareStrings(object1.toString(), object2.toString());
      } else if (object1 == null && object2 != null) {
        returnValue = 1;
      } else if (object1 != null && object2 == null) {
        returnValue = -1;
      } else {
        returnValue = 0;
      }

      return returnValue;
    }

    private int compareStrings(String string1, String string2) {
      return string1.compareTo(string2);
    }
  }

  public static class writeToCassandraStruct
      implements routines.system.IPersistableRow<writeToCassandraStruct> {
    static final byte[] commonByteArrayLock_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel =
        new byte[0];
    static byte[] commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel = new byte[0];
    protected static final int DEFAULT_HASHCODE = 1;
    protected static final int PRIME = 31;
    protected int hashCode = DEFAULT_HASHCODE;
    public boolean hashCodeDirty = true;

    public String loopKey;

    public String UserId;

    public String getUserId() {
      return this.UserId;
    }

    public String Channel;

    public String getChannel() {
      return this.Channel;
    }

    @Override
    public int hashCode() {
      if (this.hashCodeDirty) {
        final int prime = PRIME;
        int result = DEFAULT_HASHCODE;

        result = prime * result + ((this.UserId == null) ? 0 : this.UserId.hashCode());

        this.hashCode = result;
        this.hashCodeDirty = false;
      }
      return this.hashCode;
    }

    @Override
    public boolean equals(Object obj) {
      if (this == obj) return true;
      if (obj == null) return false;
      if (getClass() != obj.getClass()) return false;
      final writeToCassandraStruct other = (writeToCassandraStruct) obj;

      if (this.UserId == null) {
        if (other.UserId != null) return false;

      } else if (!this.UserId.equals(other.UserId)) return false;

      return true;
    }

    public void copyDataTo(writeToCassandraStruct other) {

      other.UserId = this.UserId;
      other.Channel = this.Channel;
    }

    public void copyKeysDataTo(writeToCassandraStruct other) {

      other.UserId = this.UserId;
    }

    private String readString(ObjectInputStream dis) throws IOException {
      String strReturn = null;
      int length = 0;
      length = dis.readInt();
      if (length == -1) {
        strReturn = null;
      } else {
        if (length > commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel.length) {
          if (length < 1024
              && commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel.length == 0) {
            commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel = new byte[1024];
          } else {
            commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel =
                new byte[2 * length];
          }
        }
        dis.readFully(
            commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel, 0, length);
        strReturn =
            new String(
                commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel,
                0,
                length,
                utf8Charset);
      }
      return strReturn;
    }

    private void writeString(String str, ObjectOutputStream dos) throws IOException {
      if (str == null) {
        dos.writeInt(-1);
      } else {
        byte[] byteArray = str.getBytes(utf8Charset);
        dos.writeInt(byteArray.length);
        dos.write(byteArray);
      }
    }

    public void readData(ObjectInputStream dis) {

      synchronized (commonByteArrayLock_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel) {
        try {

          int length = 0;

          this.UserId = readString(dis);

          this.Channel = readString(dis);

        } catch (IOException e) {
          throw new RuntimeException(e);
        }
      }
    }

    public void writeData(ObjectOutputStream dos) {
      try {

        // String

        writeString(this.UserId, dos);

        // String

        writeString(this.Channel, dos);

      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    }

    public String toString() {

      StringBuilder sb = new StringBuilder();
      sb.append(super.toString());
      sb.append("[");
      sb.append("UserId=" + UserId);
      sb.append(",Channel=" + Channel);
      sb.append("]");

      return sb.toString();
    }

    /** Compare keys */
    public int compareTo(writeToCassandraStruct other) {

      int returnValue = -1;

      returnValue = checkNullsAndCompare(this.UserId, other.UserId);
      if (returnValue != 0) {
        return returnValue;
      }

      return returnValue;
    }

    private int checkNullsAndCompare(Object object1, Object object2) {
      int returnValue = 0;
      if (object1 instanceof Comparable && object2 instanceof Comparable) {
        returnValue = ((Comparable) object1).compareTo(object2);
      } else if (object1 != null && object2 != null) {
        returnValue = compareStrings(object1.toString(), object2.toString());
      } else if (object1 == null && object2 != null) {
        returnValue = 1;
      } else if (object1 != null && object2 == null) {
        returnValue = -1;
      } else {
        returnValue = 0;
      }

      return returnValue;
    }

    private int compareStrings(String string1, String string2) {
      return string1.compareTo(string2);
    }
  }

  public static class row1Struct implements routines.system.IPersistableRow<row1Struct> {
    static final byte[] commonByteArrayLock_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel =
        new byte[0];
    static byte[] commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel = new byte[0];

    public String UserId;

    public String getUserId() {
      return this.UserId;
    }

    public String Channel;

    public String getChannel() {
      return this.Channel;
    }

    public String RootOrgId;

    public String getRootOrgId() {
      return this.RootOrgId;
    }

    private String readString(ObjectInputStream dis) throws IOException {
      String strReturn = null;
      int length = 0;
      length = dis.readInt();
      if (length == -1) {
        strReturn = null;
      } else {
        if (length > commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel.length) {
          if (length < 1024
              && commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel.length == 0) {
            commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel = new byte[1024];
          } else {
            commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel =
                new byte[2 * length];
          }
        }
        dis.readFully(
            commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel, 0, length);
        strReturn =
            new String(
                commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel,
                0,
                length,
                utf8Charset);
      }
      return strReturn;
    }

    private void writeString(String str, ObjectOutputStream dos) throws IOException {
      if (str == null) {
        dos.writeInt(-1);
      } else {
        byte[] byteArray = str.getBytes(utf8Charset);
        dos.writeInt(byteArray.length);
        dos.write(byteArray);
      }
    }

    public void readData(ObjectInputStream dis) {

      synchronized (commonByteArrayLock_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel) {
        try {

          int length = 0;

          this.UserId = readString(dis);

          this.Channel = readString(dis);

          this.RootOrgId = readString(dis);

        } catch (IOException e) {
          throw new RuntimeException(e);
        }
      }
    }

    public void writeData(ObjectOutputStream dos) {
      try {

        // String

        writeString(this.UserId, dos);

        // String

        writeString(this.Channel, dos);

        // String

        writeString(this.RootOrgId, dos);

      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    }

    public String toString() {

      StringBuilder sb = new StringBuilder();
      sb.append(super.toString());
      sb.append("[");
      sb.append("UserId=" + UserId);
      sb.append(",Channel=" + Channel);
      sb.append(",RootOrgId=" + RootOrgId);
      sb.append("]");

      return sb.toString();
    }

    /** Compare keys */
    public int compareTo(row1Struct other) {

      int returnValue = -1;

      return returnValue;
    }

    private int checkNullsAndCompare(Object object1, Object object2) {
      int returnValue = 0;
      if (object1 instanceof Comparable && object2 instanceof Comparable) {
        returnValue = ((Comparable) object1).compareTo(object2);
      } else if (object1 != null && object2 != null) {
        returnValue = compareStrings(object1.toString(), object2.toString());
      } else if (object1 == null && object2 != null) {
        returnValue = 1;
      } else if (object1 != null && object2 == null) {
        returnValue = -1;
      } else {
        returnValue = 0;
      }

      return returnValue;
    }

    private int compareStrings(String string1, String string2) {
      return string1.compareTo(string2);
    }
  }

  public static class after_tCassandraInput_1Struct
      implements routines.system.IPersistableRow<after_tCassandraInput_1Struct> {
    static final byte[] commonByteArrayLock_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel =
        new byte[0];
    static byte[] commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel = new byte[0];
    protected static final int DEFAULT_HASHCODE = 1;
    protected static final int PRIME = 31;
    protected int hashCode = DEFAULT_HASHCODE;
    public boolean hashCodeDirty = true;

    public String loopKey;

    public String UserId;

    public String getUserId() {
      return this.UserId;
    }

    public String Channel;

    public String getChannel() {
      return this.Channel;
    }

    public String RootOrgId;

    public String getRootOrgId() {
      return this.RootOrgId;
    }

    @Override
    public int hashCode() {
      if (this.hashCodeDirty) {
        final int prime = PRIME;
        int result = DEFAULT_HASHCODE;

        result = prime * result + ((this.UserId == null) ? 0 : this.UserId.hashCode());

        this.hashCode = result;
        this.hashCodeDirty = false;
      }
      return this.hashCode;
    }

    @Override
    public boolean equals(Object obj) {
      if (this == obj) return true;
      if (obj == null) return false;
      if (getClass() != obj.getClass()) return false;
      final after_tCassandraInput_1Struct other = (after_tCassandraInput_1Struct) obj;

      if (this.UserId == null) {
        if (other.UserId != null) return false;

      } else if (!this.UserId.equals(other.UserId)) return false;

      return true;
    }

    public void copyDataTo(after_tCassandraInput_1Struct other) {

      other.UserId = this.UserId;
      other.Channel = this.Channel;
      other.RootOrgId = this.RootOrgId;
    }

    public void copyKeysDataTo(after_tCassandraInput_1Struct other) {

      other.UserId = this.UserId;
    }

    private String readString(ObjectInputStream dis) throws IOException {
      String strReturn = null;
      int length = 0;
      length = dis.readInt();
      if (length == -1) {
        strReturn = null;
      } else {
        if (length > commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel.length) {
          if (length < 1024
              && commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel.length == 0) {
            commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel = new byte[1024];
          } else {
            commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel =
                new byte[2 * length];
          }
        }
        dis.readFully(
            commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel, 0, length);
        strReturn =
            new String(
                commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel,
                0,
                length,
                utf8Charset);
      }
      return strReturn;
    }

    private void writeString(String str, ObjectOutputStream dos) throws IOException {
      if (str == null) {
        dos.writeInt(-1);
      } else {
        byte[] byteArray = str.getBytes(utf8Charset);
        dos.writeInt(byteArray.length);
        dos.write(byteArray);
      }
    }

    public void readData(ObjectInputStream dis) {

      synchronized (commonByteArrayLock_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel) {
        try {

          int length = 0;

          this.UserId = readString(dis);

          this.Channel = readString(dis);

          this.RootOrgId = readString(dis);

        } catch (IOException e) {
          throw new RuntimeException(e);
        }
      }
    }

    public void writeData(ObjectOutputStream dos) {
      try {

        // String

        writeString(this.UserId, dos);

        // String

        writeString(this.Channel, dos);

        // String

        writeString(this.RootOrgId, dos);

      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    }

    public String toString() {

      StringBuilder sb = new StringBuilder();
      sb.append(super.toString());
      sb.append("[");
      sb.append("UserId=" + UserId);
      sb.append(",Channel=" + Channel);
      sb.append(",RootOrgId=" + RootOrgId);
      sb.append("]");

      return sb.toString();
    }

    /** Compare keys */
    public int compareTo(after_tCassandraInput_1Struct other) {

      int returnValue = -1;

      returnValue = checkNullsAndCompare(this.UserId, other.UserId);
      if (returnValue != 0) {
        return returnValue;
      }

      return returnValue;
    }

    private int checkNullsAndCompare(Object object1, Object object2) {
      int returnValue = 0;
      if (object1 instanceof Comparable && object2 instanceof Comparable) {
        returnValue = ((Comparable) object1).compareTo(object2);
      } else if (object1 != null && object2 != null) {
        returnValue = compareStrings(object1.toString(), object2.toString());
      } else if (object1 == null && object2 != null) {
        returnValue = 1;
      } else if (object1 != null && object2 == null) {
        returnValue = -1;
      } else {
        returnValue = 0;
      }

      return returnValue;
    }

    private int compareStrings(String string1, String string2) {
      return string1.compareTo(string2);
    }
  }

  public void tCassandraInput_1Process(final java.util.Map<String, Object> globalMap)
      throws TalendException {
    globalMap.put("tCassandraInput_1_SUBPROCESS_STATE", 0);

    final boolean execStat = this.execStat;

    String iterateId = "";

    String currentComponent = "";
    java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

    try {
      // TDI-39566 avoid throwing an useless Exception
      boolean resumeIt = true;
      if (globalResumeTicket == false && resumeEntryMethodName != null) {
        String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
        resumeIt = resumeEntryMethodName.equals(currentMethodName);
      }
      if (resumeIt || globalResumeTicket) { // start the resume
        globalResumeTicket = true;

        tCassandraInput_2Process(globalMap);

        row1Struct row1 = new row1Struct();
        toLogStruct toLog = new toLogStruct();
        writeToCassandraStruct writeToCassandra = new writeToCassandraStruct();

        /** [tFileOutputDelimited_1 begin ] start */
        ok_Hash.put("tFileOutputDelimited_1", false);
        start_Hash.put("tFileOutputDelimited_1", System.currentTimeMillis());

        currentComponent = "tFileOutputDelimited_1";

        if (execStat) {
          if (resourceMap.get("inIterateVComp") == null) {

            runStat.updateStatOnConnection("toLog" + iterateId, 0, 0);
          }
        }

        int tos_count_tFileOutputDelimited_1 = 0;

        class BytesLimit65535_tFileOutputDelimited_1 {
          public void limitLog4jByte() throws Exception {}
        }

        new BytesLimit65535_tFileOutputDelimited_1().limitLog4jByte();

        String fileName_tFileOutputDelimited_1 = "";
        fileName_tFileOutputDelimited_1 =
            (new java.io.File(context.sunbird_channel_migration_log_file))
                .getAbsolutePath()
                .replace("\\", "/");
        String fullName_tFileOutputDelimited_1 = null;
        String extension_tFileOutputDelimited_1 = null;
        String directory_tFileOutputDelimited_1 = null;
        if ((fileName_tFileOutputDelimited_1.indexOf("/") != -1)) {
          if (fileName_tFileOutputDelimited_1.lastIndexOf(".")
              < fileName_tFileOutputDelimited_1.lastIndexOf("/")) {
            fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1;
            extension_tFileOutputDelimited_1 = "";
          } else {
            fullName_tFileOutputDelimited_1 =
                fileName_tFileOutputDelimited_1.substring(
                    0, fileName_tFileOutputDelimited_1.lastIndexOf("."));
            extension_tFileOutputDelimited_1 =
                fileName_tFileOutputDelimited_1.substring(
                    fileName_tFileOutputDelimited_1.lastIndexOf("."));
          }
          directory_tFileOutputDelimited_1 =
              fileName_tFileOutputDelimited_1.substring(
                  0, fileName_tFileOutputDelimited_1.lastIndexOf("/"));
        } else {
          if (fileName_tFileOutputDelimited_1.lastIndexOf(".") != -1) {
            fullName_tFileOutputDelimited_1 =
                fileName_tFileOutputDelimited_1.substring(
                    0, fileName_tFileOutputDelimited_1.lastIndexOf("."));
            extension_tFileOutputDelimited_1 =
                fileName_tFileOutputDelimited_1.substring(
                    fileName_tFileOutputDelimited_1.lastIndexOf("."));
          } else {
            fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1;
            extension_tFileOutputDelimited_1 = "";
          }
          directory_tFileOutputDelimited_1 = "";
        }
        boolean isFileGenerated_tFileOutputDelimited_1 = true;
        java.io.File filetFileOutputDelimited_1 = new java.io.File(fileName_tFileOutputDelimited_1);
        globalMap.put("tFileOutputDelimited_1_FILE_NAME", fileName_tFileOutputDelimited_1);
        int nb_line_tFileOutputDelimited_1 = 0;
        int splitedFileNo_tFileOutputDelimited_1 = 0;
        int currentRow_tFileOutputDelimited_1 = 0;

        final String OUT_DELIM_tFileOutputDelimited_1 =
            /** Start field tFileOutputDelimited_1:FIELDSEPARATOR */
            ","
            /** End field tFileOutputDelimited_1:FIELDSEPARATOR */
            ;

        final String OUT_DELIM_ROWSEP_tFileOutputDelimited_1 =
            /** Start field tFileOutputDelimited_1:ROWSEPARATOR */
            "\n"
            /** End field tFileOutputDelimited_1:ROWSEPARATOR */
            ;

        // create directory only if not exists
        if (directory_tFileOutputDelimited_1 != null
            && directory_tFileOutputDelimited_1.trim().length() != 0) {
          java.io.File dir_tFileOutputDelimited_1 =
              new java.io.File(directory_tFileOutputDelimited_1);
          if (!dir_tFileOutputDelimited_1.exists()) {
            dir_tFileOutputDelimited_1.mkdirs();
          }
        }

        // routines.system.Row
        java.io.Writer outtFileOutputDelimited_1 = null;

        java.io.File fileToDelete_tFileOutputDelimited_1 =
            new java.io.File(fileName_tFileOutputDelimited_1);
        if (fileToDelete_tFileOutputDelimited_1.exists()) {
          fileToDelete_tFileOutputDelimited_1.delete();
        }
        outtFileOutputDelimited_1 =
            new java.io.BufferedWriter(
                new java.io.OutputStreamWriter(
                    new java.io.FileOutputStream(fileName_tFileOutputDelimited_1, false),
                    "ISO-8859-15"));
        if (filetFileOutputDelimited_1.length() == 0) {
          outtFileOutputDelimited_1.write("UserId");
          outtFileOutputDelimited_1.write(OUT_DELIM_tFileOutputDelimited_1);
          outtFileOutputDelimited_1.write("NewChannel");
          outtFileOutputDelimited_1.write(OUT_DELIM_tFileOutputDelimited_1);
          outtFileOutputDelimited_1.write("OldChannel");
          outtFileOutputDelimited_1.write(OUT_DELIM_ROWSEP_tFileOutputDelimited_1);
          outtFileOutputDelimited_1.flush();
        }

        resourceMap.put("out_tFileOutputDelimited_1", outtFileOutputDelimited_1);
        resourceMap.put("nb_line_tFileOutputDelimited_1", nb_line_tFileOutputDelimited_1);

        /** [tFileOutputDelimited_1 begin ] stop */

        /** [tCassandraOutput_1 begin ] start */
        ok_Hash.put("tCassandraOutput_1", false);
        start_Hash.put("tCassandraOutput_1", System.currentTimeMillis());

        currentComponent = "tCassandraOutput_1";

        if (execStat) {
          if (resourceMap.get("inIterateVComp") == null) {

            runStat.updateStatOnConnection("writeToCassandra" + iterateId, 0, 0);
          }
        }

        int tos_count_tCassandraOutput_1 = 0;

        class BytesLimit65535_tCassandraOutput_1 {
          public void limitLog4jByte() throws Exception {}
        }

        new BytesLimit65535_tCassandraOutput_1().limitLog4jByte();

        com.datastax.driver.core.Cluster cluster_tCassandraOutput_1 =
            (com.datastax.driver.core.Cluster) globalMap.get("cluster_tCassandraConnection_1");
        com.datastax.driver.core.Session connection_tCassandraOutput_1 =
            (com.datastax.driver.core.Session) globalMap.get("connection_tCassandraConnection_1");

        int nb_line_tCassandraOutput_1 = 0;
        com.datastax.driver.core.PreparedStatement prepareStmt_tCassandraOutput_1 = null;
        prepareStmt_tCassandraOutput_1 =
            connection_tCassandraOutput_1.prepare(
                "UPDATE "
                    + StringHandling.DQUOTE(context.sunbird_cassandra_keyspace)
                    + "."
                    + StringHandling.DQUOTE("user")
                    + " SET channel=? WHERE id=?");
        com.datastax.driver.core.BoundStatement boundStmt_tCassandraOutput_1 = null;

        java.util.List<String> columns_tCassandraOutput_1 = new java.util.ArrayList<String>();

        columns_tCassandraOutput_1.add("Channel");

        columns_tCassandraOutput_1.add("UserId");

        org.talend.bigdata.cassandra.BatchExecutor cassandraBatchExec_tCassandraOutput_1 =
            new org.talend.bigdata.cassandra.BatchExecutor(
                connection_tCassandraOutput_1,
                StringHandling.DQUOTE(context.sunbird_cassandra_keyspace),
                StringHandling.DQUOTE("user"),
                columns_tCassandraOutput_1,
                org.talend.bigdata.cassandra.BatchGroupingKey.fromString("PARTITION"),
                1000,
                true,
                5);

        /** [tCassandraOutput_1 begin ] stop */

        /** [tMap_1 begin ] start */
        ok_Hash.put("tMap_1", false);
        start_Hash.put("tMap_1", System.currentTimeMillis());

        currentComponent = "tMap_1";

        if (execStat) {
          if (resourceMap.get("inIterateVComp") == null) {

            runStat.updateStatOnConnection("row1" + iterateId, 0, 0);
          }
        }

        int tos_count_tMap_1 = 0;

        class BytesLimit65535_tMap_1 {
          public void limitLog4jByte() throws Exception {}
        }

        new BytesLimit65535_tMap_1().limitLog4jByte();

        // ###############################
        // # Lookup's keys initialization

        org.talend.designer.components.lookup.memory.AdvancedMemoryLookup<row2Struct>
            tHash_Lookup_row2 =
                (org.talend.designer.components.lookup.memory.AdvancedMemoryLookup<row2Struct>)
                    ((org.talend.designer.components.lookup.memory.AdvancedMemoryLookup<row2Struct>)
                        globalMap.get("tHash_Lookup_row2"));

        row2Struct row2HashKey = new row2Struct();
        row2Struct row2Default = new row2Struct();
        // ###############################

        // ###############################
        // # Vars initialization
        class Var__tMap_1__Struct {}
        Var__tMap_1__Struct Var__tMap_1 = new Var__tMap_1__Struct();
        // ###############################

        // ###############################
        // # Outputs initialization
        toLogStruct toLog_tmp = new toLogStruct();
        writeToCassandraStruct writeToCassandra_tmp = new writeToCassandraStruct();
        // ###############################

        /** [tMap_1 begin ] stop */

        /** [tCassandraInput_1 begin ] start */
        ok_Hash.put("tCassandraInput_1", false);
        start_Hash.put("tCassandraInput_1", System.currentTimeMillis());

        currentComponent = "tCassandraInput_1";

        int tos_count_tCassandraInput_1 = 0;

        class BytesLimit65535_tCassandraInput_1 {
          public void limitLog4jByte() throws Exception {}
        }

        new BytesLimit65535_tCassandraInput_1().limitLog4jByte();

        com.datastax.driver.core.Cluster cluster_tCassandraInput_1 =
            (com.datastax.driver.core.Cluster) globalMap.get("cluster_tCassandraConnection_1");
        com.datastax.driver.core.Session connection_tCassandraInput_1 =
            (com.datastax.driver.core.Session) globalMap.get("connection_tCassandraConnection_1");

        com.datastax.driver.core.ResultSet rs_tCassandraInput_1 =
            connection_tCassandraInput_1.execute("select id, channel, rootorgid from sunbird.user");
        int nb_line_tCassandraInput_1 = 0;
        for (com.datastax.driver.core.Row row_tCassandraInput_1 : rs_tCassandraInput_1) {
          if (row_tCassandraInput_1.isNull("\"id\"")) {
            row1.UserId = null;
          } else {

            row1.UserId = row_tCassandraInput_1.getString("\"id\"");
          }

          if (row_tCassandraInput_1.isNull("\"channel\"")) {
            row1.Channel = null;
          } else {

            row1.Channel = row_tCassandraInput_1.getString("\"channel\"");
          }

          if (row_tCassandraInput_1.isNull("\"rootorgid\"")) {
            row1.RootOrgId = null;
          } else {

            row1.RootOrgId = row_tCassandraInput_1.getString("\"rootorgid\"");
          }

          nb_line_tCassandraInput_1++;

          /** [tCassandraInput_1 begin ] stop */

          /** [tCassandraInput_1 main ] start */
          currentComponent = "tCassandraInput_1";

          tos_count_tCassandraInput_1++;

          /** [tCassandraInput_1 main ] stop */

          /** [tCassandraInput_1 process_data_begin ] start */
          currentComponent = "tCassandraInput_1";

          /** [tCassandraInput_1 process_data_begin ] stop */

          /** [tMap_1 main ] start */
          currentComponent = "tMap_1";

          // row1
          // row1

          if (execStat) {
            runStat.updateStatOnConnection("row1" + iterateId, 1, 1);
          }

          boolean hasCasePrimitiveKeyWithNull_tMap_1 = false;

          // ###############################
          // # Input tables (lookups)
          boolean rejectedInnerJoin_tMap_1 = false;
          boolean mainRowRejected_tMap_1 = false;

          ///////////////////////////////////////////////
          // Starting Lookup Table "row2"
          ///////////////////////////////////////////////

          boolean forceLooprow2 = false;

          row2Struct row2ObjectFromLookup = null;

          if (!rejectedInnerJoin_tMap_1) { // G_TM_M_020

            hasCasePrimitiveKeyWithNull_tMap_1 = false;

            row2HashKey.OrgId = row1.RootOrgId;

            row2HashKey.hashCodeDirty = true;

            tHash_Lookup_row2.lookup(row2HashKey);

            if (!tHash_Lookup_row2.hasNext()) { // G_TM_M_090

              rejectedInnerJoin_tMap_1 = true;

              forceLooprow2 = true;
            } // G_TM_M_090

          } // G_TM_M_020
          else { // G 20 - G 21
            forceLooprow2 = true;
          } // G 21

          row2Struct row2 = null;

          while ((tHash_Lookup_row2 != null && tHash_Lookup_row2.hasNext())
              || forceLooprow2) { // G_TM_M_043

            // CALL close loop of lookup 'row2'

            row2Struct fromLookup_row2 = null;
            row2 = row2Default;

            if (!forceLooprow2) { // G 46

              fromLookup_row2 = tHash_Lookup_row2.next();

              if (fromLookup_row2 != null) {
                row2 = fromLookup_row2;
              }
            } // G 46

            forceLooprow2 = false;

            // ###############################
            { // start of Var scope

              // ###############################
              // # Vars tables

              Var__tMap_1__Struct Var = Var__tMap_1; // ###############################
              // ###############################
              // # Output tables

              toLog = null;
              writeToCassandra = null;

              if (!rejectedInnerJoin_tMap_1) {

                // # Output table : 'toLog'
                toLog_tmp.UserId = row1.UserId;
                toLog_tmp.NewChannel = row2.Channel;
                toLog_tmp.OldChannel = row1.Channel;
                toLog = toLog_tmp;

                // # Output table : 'writeToCassandra'
                writeToCassandra_tmp.UserId = row1.UserId;
                writeToCassandra_tmp.Channel = row2.Channel;
                writeToCassandra = writeToCassandra_tmp;
              } // closing inner join bracket (2)
              // ###############################

            } // end of Var scope

            rejectedInnerJoin_tMap_1 = false;

            tos_count_tMap_1++;

            /** [tMap_1 main ] stop */

            /** [tMap_1 process_data_begin ] start */
            currentComponent = "tMap_1";

            /** [tMap_1 process_data_begin ] stop */
            // Start of branch "toLog"
            if (toLog != null) {

              /** [tFileOutputDelimited_1 main ] start */
              currentComponent = "tFileOutputDelimited_1";

              // toLog
              // toLog

              if (execStat) {
                runStat.updateStatOnConnection("toLog" + iterateId, 1, 1);
              }

              StringBuilder sb_tFileOutputDelimited_1 = new StringBuilder();
              if (toLog.UserId != null) {
                sb_tFileOutputDelimited_1.append(toLog.UserId);
              }
              sb_tFileOutputDelimited_1.append(OUT_DELIM_tFileOutputDelimited_1);
              if (toLog.NewChannel != null) {
                sb_tFileOutputDelimited_1.append(toLog.NewChannel);
              }
              sb_tFileOutputDelimited_1.append(OUT_DELIM_tFileOutputDelimited_1);
              if (toLog.OldChannel != null) {
                sb_tFileOutputDelimited_1.append(toLog.OldChannel);
              }
              sb_tFileOutputDelimited_1.append(OUT_DELIM_ROWSEP_tFileOutputDelimited_1);

              nb_line_tFileOutputDelimited_1++;
              resourceMap.put("nb_line_tFileOutputDelimited_1", nb_line_tFileOutputDelimited_1);

              outtFileOutputDelimited_1.write(sb_tFileOutputDelimited_1.toString());

              tos_count_tFileOutputDelimited_1++;

              /** [tFileOutputDelimited_1 main ] stop */

              /** [tFileOutputDelimited_1 process_data_begin ] start */
              currentComponent = "tFileOutputDelimited_1";

              /** [tFileOutputDelimited_1 process_data_begin ] stop */

              /** [tFileOutputDelimited_1 process_data_end ] start */
              currentComponent = "tFileOutputDelimited_1";

              /** [tFileOutputDelimited_1 process_data_end ] stop */
            } // End of branch "toLog"

            // Start of branch "writeToCassandra"
            if (writeToCassandra != null) {

              /** [tCassandraOutput_1 main ] start */
              currentComponent = "tCassandraOutput_1";

              // writeToCassandra
              // writeToCassandra

              if (execStat) {
                runStat.updateStatOnConnection("writeToCassandra" + iterateId, 1, 1);
              }

              boundStmt_tCassandraOutput_1 =
                  new com.datastax.driver.core.BoundStatement(prepareStmt_tCassandraOutput_1);

              if (writeToCassandra.Channel == null) {
                boundStmt_tCassandraOutput_1.setToNull(0);
              } else {
                boundStmt_tCassandraOutput_1.setString(0, writeToCassandra.Channel);
              }
              if (writeToCassandra.UserId == null) {
                boundStmt_tCassandraOutput_1.setToNull(1);
              } else {
                boundStmt_tCassandraOutput_1.setString(1, writeToCassandra.UserId);
              }

              cassandraBatchExec_tCassandraOutput_1.addOrExecBatch(boundStmt_tCassandraOutput_1);

              nb_line_tCassandraOutput_1++;

              tos_count_tCassandraOutput_1++;

              /** [tCassandraOutput_1 main ] stop */

              /** [tCassandraOutput_1 process_data_begin ] start */
              currentComponent = "tCassandraOutput_1";

              /** [tCassandraOutput_1 process_data_begin ] stop */

              /** [tCassandraOutput_1 process_data_end ] start */
              currentComponent = "tCassandraOutput_1";

              /** [tCassandraOutput_1 process_data_end ] stop */
            } // End of branch "writeToCassandra"
          } // close loop of lookup 'row2' // G_TM_M_043

          /** [tMap_1 process_data_end ] start */
          currentComponent = "tMap_1";

          /** [tMap_1 process_data_end ] stop */

          /** [tCassandraInput_1 process_data_end ] start */
          currentComponent = "tCassandraInput_1";

          /** [tCassandraInput_1 process_data_end ] stop */

          /** [tCassandraInput_1 end ] start */
          currentComponent = "tCassandraInput_1";
        }
        globalMap.put("tCassandraInput_1_NB_LINE", nb_line_tCassandraInput_1);

        ok_Hash.put("tCassandraInput_1", true);
        end_Hash.put("tCassandraInput_1", System.currentTimeMillis());

        /** [tCassandraInput_1 end ] stop */

        /** [tMap_1 end ] start */
        currentComponent = "tMap_1";

        // ###############################
        // # Lookup hashes releasing
        if (tHash_Lookup_row2 != null) {
          tHash_Lookup_row2.endGet();
        }
        globalMap.remove("tHash_Lookup_row2");

        // ###############################

        if (execStat) {
          if (resourceMap.get("inIterateVComp") == null
              || !((Boolean) resourceMap.get("inIterateVComp"))) {
            runStat.updateStatOnConnection("row1" + iterateId, 2, 0);
          }
        }

        ok_Hash.put("tMap_1", true);
        end_Hash.put("tMap_1", System.currentTimeMillis());

        /** [tMap_1 end ] stop */

        /** [tFileOutputDelimited_1 end ] start */
        currentComponent = "tFileOutputDelimited_1";

        if (outtFileOutputDelimited_1 != null) {
          outtFileOutputDelimited_1.flush();
          outtFileOutputDelimited_1.close();
        }

        globalMap.put("tFileOutputDelimited_1_NB_LINE", nb_line_tFileOutputDelimited_1);
        globalMap.put("tFileOutputDelimited_1_FILE_NAME", fileName_tFileOutputDelimited_1);

        resourceMap.put("finish_tFileOutputDelimited_1", true);

        if (execStat) {
          if (resourceMap.get("inIterateVComp") == null
              || !((Boolean) resourceMap.get("inIterateVComp"))) {
            runStat.updateStatOnConnection("toLog" + iterateId, 2, 0);
          }
        }

        ok_Hash.put("tFileOutputDelimited_1", true);
        end_Hash.put("tFileOutputDelimited_1", System.currentTimeMillis());

        /** [tFileOutputDelimited_1 end ] stop */

        /** [tCassandraOutput_1 end ] start */
        currentComponent = "tCassandraOutput_1";

        cassandraBatchExec_tCassandraOutput_1.endBatch();
        globalMap.put("tCassandraOutput_1_NB_LINE", nb_line_tCassandraOutput_1);

        if (execStat) {
          if (resourceMap.get("inIterateVComp") == null
              || !((Boolean) resourceMap.get("inIterateVComp"))) {
            runStat.updateStatOnConnection("writeToCassandra" + iterateId, 2, 0);
          }
        }

        ok_Hash.put("tCassandraOutput_1", true);
        end_Hash.put("tCassandraOutput_1", System.currentTimeMillis());

        /** [tCassandraOutput_1 end ] stop */
      } // end the resume

      if (resumeEntryMethodName == null || globalResumeTicket) {
        resumeUtil.addLog(
            "CHECKPOINT",
            "CONNECTION:SUBJOB_OK:tCassandraInput_1:OnSubjobOk",
            "",
            Thread.currentThread().getId() + "",
            "",
            "",
            "",
            "",
            "");
      }

      if (execStat) {
        runStat.updateStatOnConnection("OnSubjobOk1", 0, "ok");
      }

      tCassandraClose_1Process(globalMap);

    } catch (java.lang.Exception e) {

      TalendException te = new TalendException(e, currentComponent, globalMap);

      throw te;
    } catch (java.lang.Error error) {

      runStat.stopThreadStat();

      throw error;
    } finally {

      // free memory for "tMap_1"
      globalMap.remove("tHash_Lookup_row2");

      try {

        /** [tCassandraInput_1 finally ] start */
        currentComponent = "tCassandraInput_1";

        /** [tCassandraInput_1 finally ] stop */

        /** [tMap_1 finally ] start */
        currentComponent = "tMap_1";

        /** [tMap_1 finally ] stop */

        /** [tFileOutputDelimited_1 finally ] start */
        currentComponent = "tFileOutputDelimited_1";

        if (resourceMap.get("finish_tFileOutputDelimited_1") == null) {

          java.io.Writer outtFileOutputDelimited_1 =
              (java.io.Writer) resourceMap.get("out_tFileOutputDelimited_1");
          if (outtFileOutputDelimited_1 != null) {
            outtFileOutputDelimited_1.flush();
            outtFileOutputDelimited_1.close();
          }
        }

        /** [tFileOutputDelimited_1 finally ] stop */

        /** [tCassandraOutput_1 finally ] start */
        currentComponent = "tCassandraOutput_1";

        /** [tCassandraOutput_1 finally ] stop */
      } catch (java.lang.Exception e) {
        // ignore
      } catch (java.lang.Error error) {
        // ignore
      }
      resourceMap = null;
    }

    globalMap.put("tCassandraInput_1_SUBPROCESS_STATE", 1);
  }

  public void tCassandraClose_1Process(final java.util.Map<String, Object> globalMap)
      throws TalendException {
    globalMap.put("tCassandraClose_1_SUBPROCESS_STATE", 0);

    final boolean execStat = this.execStat;

    String iterateId = "";

    String currentComponent = "";
    java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

    try {
      // TDI-39566 avoid throwing an useless Exception
      boolean resumeIt = true;
      if (globalResumeTicket == false && resumeEntryMethodName != null) {
        String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
        resumeIt = resumeEntryMethodName.equals(currentMethodName);
      }
      if (resumeIt || globalResumeTicket) { // start the resume
        globalResumeTicket = true;

        /** [tCassandraClose_1 begin ] start */
        ok_Hash.put("tCassandraClose_1", false);
        start_Hash.put("tCassandraClose_1", System.currentTimeMillis());

        currentComponent = "tCassandraClose_1";

        int tos_count_tCassandraClose_1 = 0;

        class BytesLimit65535_tCassandraClose_1 {
          public void limitLog4jByte() throws Exception {}
        }

        new BytesLimit65535_tCassandraClose_1().limitLog4jByte();

        /** [tCassandraClose_1 begin ] stop */

        /** [tCassandraClose_1 main ] start */
        currentComponent = "tCassandraClose_1";

        com.datastax.driver.core.Cluster cluster_tCassandraClose_1 =
            (com.datastax.driver.core.Cluster) globalMap.get("cluster_tCassandraConnection_1");
        com.datastax.driver.core.Session connection_tCassandraClose_1 =
            (com.datastax.driver.core.Session) globalMap.get("connection_tCassandraConnection_1");
        if (connection_tCassandraClose_1 != null) {
          connection_tCassandraClose_1.close();
        }
        if (cluster_tCassandraClose_1 != null) {
          cluster_tCassandraClose_1.close();
        }

        tos_count_tCassandraClose_1++;

        /** [tCassandraClose_1 main ] stop */

        /** [tCassandraClose_1 process_data_begin ] start */
        currentComponent = "tCassandraClose_1";

        /** [tCassandraClose_1 process_data_begin ] stop */

        /** [tCassandraClose_1 process_data_end ] start */
        currentComponent = "tCassandraClose_1";

        /** [tCassandraClose_1 process_data_end ] stop */

        /** [tCassandraClose_1 end ] start */
        currentComponent = "tCassandraClose_1";

        ok_Hash.put("tCassandraClose_1", true);
        end_Hash.put("tCassandraClose_1", System.currentTimeMillis());

        /** [tCassandraClose_1 end ] stop */
      } // end the resume

    } catch (java.lang.Exception e) {

      TalendException te = new TalendException(e, currentComponent, globalMap);

      throw te;
    } catch (java.lang.Error error) {

      runStat.stopThreadStat();

      throw error;
    } finally {

      try {

        /** [tCassandraClose_1 finally ] start */
        currentComponent = "tCassandraClose_1";

        /** [tCassandraClose_1 finally ] stop */
      } catch (java.lang.Exception e) {
        // ignore
      } catch (java.lang.Error error) {
        // ignore
      }
      resourceMap = null;
    }

    globalMap.put("tCassandraClose_1_SUBPROCESS_STATE", 1);
  }

  public static class row2Struct
      implements routines.system.IPersistableComparableLookupRow<row2Struct> {
    static final byte[] commonByteArrayLock_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel =
        new byte[0];
    static byte[] commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel = new byte[0];
    protected static final int DEFAULT_HASHCODE = 1;
    protected static final int PRIME = 31;
    protected int hashCode = DEFAULT_HASHCODE;
    public boolean hashCodeDirty = true;

    public String loopKey;

    public String OrgId;

    public String getOrgId() {
      return this.OrgId;
    }

    public String Channel;

    public String getChannel() {
      return this.Channel;
    }

    @Override
    public int hashCode() {
      if (this.hashCodeDirty) {
        final int prime = PRIME;
        int result = DEFAULT_HASHCODE;

        result = prime * result + ((this.OrgId == null) ? 0 : this.OrgId.hashCode());

        this.hashCode = result;
        this.hashCodeDirty = false;
      }
      return this.hashCode;
    }

    @Override
    public boolean equals(Object obj) {
      if (this == obj) return true;
      if (obj == null) return false;
      if (getClass() != obj.getClass()) return false;
      final row2Struct other = (row2Struct) obj;

      if (this.OrgId == null) {
        if (other.OrgId != null) return false;

      } else if (!this.OrgId.equals(other.OrgId)) return false;

      return true;
    }

    public void copyDataTo(row2Struct other) {

      other.OrgId = this.OrgId;
      other.Channel = this.Channel;
    }

    public void copyKeysDataTo(row2Struct other) {

      other.OrgId = this.OrgId;
    }

    private String readString(ObjectInputStream dis) throws IOException {
      String strReturn = null;
      int length = 0;
      length = dis.readInt();
      if (length == -1) {
        strReturn = null;
      } else {
        if (length > commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel.length) {
          if (length < 1024
              && commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel.length == 0) {
            commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel = new byte[1024];
          } else {
            commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel =
                new byte[2 * length];
          }
        }
        dis.readFully(
            commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel, 0, length);
        strReturn =
            new String(
                commonByteArray_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel,
                0,
                length,
                utf8Charset);
      }
      return strReturn;
    }

    private void writeString(String str, ObjectOutputStream dos) throws IOException {
      if (str == null) {
        dos.writeInt(-1);
      } else {
        byte[] byteArray = str.getBytes(utf8Charset);
        dos.writeInt(byteArray.length);
        dos.write(byteArray);
      }
    }

    private String readString(DataInputStream dis, ObjectInputStream ois) throws IOException {
      String strReturn = null;
      int length = 0;
      length = dis.readInt();
      if (length == -1) {
        strReturn = null;
      } else {
        byte[] byteArray = new byte[length];
        dis.read(byteArray);
        strReturn = new String(byteArray, utf8Charset);
      }
      return strReturn;
    }

    private void writeString(String str, DataOutputStream dos, ObjectOutputStream oos)
        throws IOException {
      if (str == null) {
        dos.writeInt(-1);
      } else {
        byte[] byteArray = str.getBytes(utf8Charset);
        dos.writeInt(byteArray.length);
        dos.write(byteArray);
      }
    }

    public void readKeysData(ObjectInputStream dis) {

      synchronized (commonByteArrayLock_USEREXTERNALIDMIGRATION_UserMigrationUpdateChannel) {
        try {

          int length = 0;

          this.OrgId = readString(dis);

        } catch (IOException e) {
          throw new RuntimeException(e);
        }
      }
    }

    public void writeKeysData(ObjectOutputStream dos) {
      try {

        // String

        writeString(this.OrgId, dos);

      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    }

    /** Fill Values data by reading ObjectInputStream. */
    public void readValuesData(DataInputStream dis, ObjectInputStream ois) {
      try {

        int length = 0;

        this.Channel = readString(dis, ois);

      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    }

    /** Return a byte array which represents Values data. */
    public void writeValuesData(DataOutputStream dos, ObjectOutputStream oos) {
      try {

        writeString(this.Channel, dos, oos);

      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    }

    public String toString() {

      StringBuilder sb = new StringBuilder();
      sb.append(super.toString());
      sb.append("[");
      sb.append("OrgId=" + OrgId);
      sb.append(",Channel=" + Channel);
      sb.append("]");

      return sb.toString();
    }

    /** Compare keys */
    public int compareTo(row2Struct other) {

      int returnValue = -1;

      returnValue = checkNullsAndCompare(this.OrgId, other.OrgId);
      if (returnValue != 0) {
        return returnValue;
      }

      return returnValue;
    }

    private int checkNullsAndCompare(Object object1, Object object2) {
      int returnValue = 0;
      if (object1 instanceof Comparable && object2 instanceof Comparable) {
        returnValue = ((Comparable) object1).compareTo(object2);
      } else if (object1 != null && object2 != null) {
        returnValue = compareStrings(object1.toString(), object2.toString());
      } else if (object1 == null && object2 != null) {
        returnValue = 1;
      } else if (object1 != null && object2 == null) {
        returnValue = -1;
      } else {
        returnValue = 0;
      }

      return returnValue;
    }

    private int compareStrings(String string1, String string2) {
      return string1.compareTo(string2);
    }
  }

  public void tCassandraInput_2Process(final java.util.Map<String, Object> globalMap)
      throws TalendException {
    globalMap.put("tCassandraInput_2_SUBPROCESS_STATE", 0);

    final boolean execStat = this.execStat;

    String iterateId = "";

    String currentComponent = "";
    java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

    try {
      // TDI-39566 avoid throwing an useless Exception
      boolean resumeIt = true;
      if (globalResumeTicket == false && resumeEntryMethodName != null) {
        String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
        resumeIt = resumeEntryMethodName.equals(currentMethodName);
      }
      if (resumeIt || globalResumeTicket) { // start the resume
        globalResumeTicket = true;

        row2Struct row2 = new row2Struct();

        /** [tAdvancedHash_row2 begin ] start */
        ok_Hash.put("tAdvancedHash_row2", false);
        start_Hash.put("tAdvancedHash_row2", System.currentTimeMillis());

        currentComponent = "tAdvancedHash_row2";

        if (execStat) {
          if (resourceMap.get("inIterateVComp") == null) {

            runStat.updateStatOnConnection("row2" + iterateId, 0, 0);
          }
        }

        int tos_count_tAdvancedHash_row2 = 0;

        class BytesLimit65535_tAdvancedHash_row2 {
          public void limitLog4jByte() throws Exception {}
        }

        new BytesLimit65535_tAdvancedHash_row2().limitLog4jByte();

        // connection name:row2
        // source node:tCassandraInput_2 - inputs:(after_tCassandraInput_1) outputs:(row2,row2) |
        // target node:tAdvancedHash_row2 - inputs:(row2) outputs:()
        // linked node: tMap_1 - inputs:(row1,row2) outputs:(toLog,writeToCassandra)

        org.talend.designer.components.lookup.common.ICommonLookup.MATCHING_MODE
            matchingModeEnum_row2 =
                org.talend.designer.components.lookup.common.ICommonLookup.MATCHING_MODE
                    .ALL_MATCHES;

        org.talend.designer.components.lookup.memory.AdvancedMemoryLookup<row2Struct>
            tHash_Lookup_row2 =
                org.talend.designer.components.lookup.memory.AdvancedMemoryLookup
                    .<row2Struct>getLookup(matchingModeEnum_row2);

        globalMap.put("tHash_Lookup_row2", tHash_Lookup_row2);

        /** [tAdvancedHash_row2 begin ] stop */

        /** [tCassandraInput_2 begin ] start */
        ok_Hash.put("tCassandraInput_2", false);
        start_Hash.put("tCassandraInput_2", System.currentTimeMillis());

        currentComponent = "tCassandraInput_2";

        int tos_count_tCassandraInput_2 = 0;

        class BytesLimit65535_tCassandraInput_2 {
          public void limitLog4jByte() throws Exception {}
        }

        new BytesLimit65535_tCassandraInput_2().limitLog4jByte();

        com.datastax.driver.core.Cluster cluster_tCassandraInput_2 =
            (com.datastax.driver.core.Cluster) globalMap.get("cluster_tCassandraConnection_1");
        com.datastax.driver.core.Session connection_tCassandraInput_2 =
            (com.datastax.driver.core.Session) globalMap.get("connection_tCassandraConnection_1");

        com.datastax.driver.core.ResultSet rs_tCassandraInput_2 =
            connection_tCassandraInput_2.execute(
                "select id, channel from sunbird.organisation where isrootorg=true allow filtering");
        int nb_line_tCassandraInput_2 = 0;
        for (com.datastax.driver.core.Row row_tCassandraInput_2 : rs_tCassandraInput_2) {
          if (row_tCassandraInput_2.isNull("\"id\"")) {
            row2.OrgId = null;
          } else {

            row2.OrgId = row_tCassandraInput_2.getString("\"id\"");
          }

          if (row_tCassandraInput_2.isNull("\"channel\"")) {
            row2.Channel = null;
          } else {

            row2.Channel = row_tCassandraInput_2.getString("\"channel\"");
          }

          nb_line_tCassandraInput_2++;

          /** [tCassandraInput_2 begin ] stop */

          /** [tCassandraInput_2 main ] start */
          currentComponent = "tCassandraInput_2";

          tos_count_tCassandraInput_2++;

          /** [tCassandraInput_2 main ] stop */

          /** [tCassandraInput_2 process_data_begin ] start */
          currentComponent = "tCassandraInput_2";

          /** [tCassandraInput_2 process_data_begin ] stop */

          /** [tAdvancedHash_row2 main ] start */
          currentComponent = "tAdvancedHash_row2";

          // row2
          // row2

          if (execStat) {
            runStat.updateStatOnConnection("row2" + iterateId, 1, 1);
          }

          row2Struct row2_HashRow = new row2Struct();

          row2_HashRow.OrgId = row2.OrgId;

          row2_HashRow.Channel = row2.Channel;

          tHash_Lookup_row2.put(row2_HashRow);

          tos_count_tAdvancedHash_row2++;

          /** [tAdvancedHash_row2 main ] stop */

          /** [tAdvancedHash_row2 process_data_begin ] start */
          currentComponent = "tAdvancedHash_row2";

          /** [tAdvancedHash_row2 process_data_begin ] stop */

          /** [tAdvancedHash_row2 process_data_end ] start */
          currentComponent = "tAdvancedHash_row2";

          /** [tAdvancedHash_row2 process_data_end ] stop */

          /** [tCassandraInput_2 process_data_end ] start */
          currentComponent = "tCassandraInput_2";

          /** [tCassandraInput_2 process_data_end ] stop */

          /** [tCassandraInput_2 end ] start */
          currentComponent = "tCassandraInput_2";
        }
        globalMap.put("tCassandraInput_2_NB_LINE", nb_line_tCassandraInput_2);

        ok_Hash.put("tCassandraInput_2", true);
        end_Hash.put("tCassandraInput_2", System.currentTimeMillis());

        /** [tCassandraInput_2 end ] stop */

        /** [tAdvancedHash_row2 end ] start */
        currentComponent = "tAdvancedHash_row2";

        tHash_Lookup_row2.endPut();

        if (execStat) {
          if (resourceMap.get("inIterateVComp") == null
              || !((Boolean) resourceMap.get("inIterateVComp"))) {
            runStat.updateStatOnConnection("row2" + iterateId, 2, 0);
          }
        }

        ok_Hash.put("tAdvancedHash_row2", true);
        end_Hash.put("tAdvancedHash_row2", System.currentTimeMillis());

        /** [tAdvancedHash_row2 end ] stop */
      } // end the resume

    } catch (java.lang.Exception e) {

      TalendException te = new TalendException(e, currentComponent, globalMap);

      throw te;
    } catch (java.lang.Error error) {

      runStat.stopThreadStat();

      throw error;
    } finally {

      try {

        /** [tCassandraInput_2 finally ] start */
        currentComponent = "tCassandraInput_2";

        /** [tCassandraInput_2 finally ] stop */

        /** [tAdvancedHash_row2 finally ] start */
        currentComponent = "tAdvancedHash_row2";

        /** [tAdvancedHash_row2 finally ] stop */
      } catch (java.lang.Exception e) {
        // ignore
      } catch (java.lang.Error error) {
        // ignore
      }
      resourceMap = null;
    }

    globalMap.put("tCassandraInput_2_SUBPROCESS_STATE", 1);
  }

  public String resuming_logs_dir_path = null;
  public String resuming_checkpoint_path = null;
  public String parent_part_launcher = null;
  private String resumeEntryMethodName = null;
  private boolean globalResumeTicket = false;

  public boolean watch = false;
  // portStats is null, it means don't execute the statistics
  public Integer portStats = null;
  public int portTraces = 4334;
  public String clientHost;
  public String defaultClientHost = "localhost";
  public String contextStr = "Default";
  public boolean isDefaultContext = true;
  public String pid = "0";
  public String rootPid = null;
  public String fatherPid = null;
  public String fatherNode = null;
  public long startTime = 0;
  public boolean isChildJob = false;
  public String log4jLevel = "";

  private boolean execStat = true;

  private ThreadLocal<java.util.Map<String, String>> threadLocal =
      new ThreadLocal<java.util.Map<String, String>>() {
        protected java.util.Map<String, String> initialValue() {
          java.util.Map<String, String> threadRunResultMap =
              new java.util.HashMap<String, String>();
          threadRunResultMap.put("errorCode", null);
          threadRunResultMap.put("status", "");
          return threadRunResultMap;
        };
      };

  private PropertiesWithType context_param = new PropertiesWithType();
  public java.util.Map<String, Object> parentContextMap = new java.util.HashMap<String, Object>();

  public String status = "";

  public static void main(String[] args) {
    final UserMigrationUpdateChannel UserMigrationUpdateChannelClass =
        new UserMigrationUpdateChannel();

    int exitCode = UserMigrationUpdateChannelClass.runJobInTOS(args);

    System.exit(exitCode);
  }

  public String[][] runJob(String[] args) {

    int exitCode = runJobInTOS(args);
    String[][] bufferValue = new String[][] {{Integer.toString(exitCode)}};

    return bufferValue;
  }

  public boolean hastBufferOutputComponent() {
    boolean hastBufferOutput = false;

    return hastBufferOutput;
  }

  public int runJobInTOS(String[] args) {
    // reset status
    status = "";

    String lastStr = "";
    for (String arg : args) {
      if (arg.equalsIgnoreCase("--context_param")) {
        lastStr = arg;
      } else if (lastStr.equals("")) {
        evalParam(arg);
      } else {
        evalParam(lastStr + " " + arg);
        lastStr = "";
      }
    }

    if (clientHost == null) {
      clientHost = defaultClientHost;
    }

    if (pid == null || "0".equals(pid)) {
      pid = TalendString.getAsciiRandomString(6);
    }

    if (rootPid == null) {
      rootPid = pid;
    }
    if (fatherPid == null) {
      fatherPid = pid;
    } else {
      isChildJob = true;
    }

    if (portStats != null) {
      // portStats = -1; //for testing
      if (portStats < 0 || portStats > 65535) {
        // issue:10869, the portStats is invalid, so this client socket can't open
        System.err.println("The statistics socket port " + portStats + " is invalid.");
        execStat = false;
      }
    } else {
      execStat = false;
    }

    try {
      // call job/subjob with an existing context, like: --context=production. if without this
      // parameter, there will use the default context instead.
      java.io.InputStream inContext =
          UserMigrationUpdateChannel.class
              .getClassLoader()
              .getResourceAsStream(
                  "userexternalidmigration/usermigrationupdatechannel_0_1/contexts/"
                      + contextStr
                      + ".properties");
      if (inContext == null) {
        inContext =
            UserMigrationUpdateChannel.class
                .getClassLoader()
                .getResourceAsStream("config/contexts/" + contextStr + ".properties");
      }
      if (inContext != null) {
        // defaultProps is in order to keep the original context value
        defaultProps.load(inContext);
        inContext.close();
        context = new ContextProperties(defaultProps);
      } else if (!isDefaultContext) {
        // print info and job continue to run, for case: context_param is not empty.
        System.err.println("Could not find the context " + contextStr);
      }

      if (!context_param.isEmpty()) {
        context.putAll(context_param);
        // set types for params from parentJobs
        for (Object key : context_param.keySet()) {
          String context_key = key.toString();
          String context_type = context_param.getContextType(context_key);
          context.setContextType(context_key, context_type);
        }
      }
      context.setContextType("sunbird_cassandra_keyspace", "id_String");

      context.sunbird_cassandra_keyspace =
          (String) context.getProperty("sunbird_cassandra_keyspace");
      context.setContextType("sunbird_cassandra_password", "id_Password");

      String pwd_sunbird_cassandra_password_value =
          context.getProperty("sunbird_cassandra_password");
      context.sunbird_cassandra_password = null;
      if (pwd_sunbird_cassandra_password_value != null) {
        if (context_param.containsKey(
            "sunbird_cassandra_password")) { // no need to decrypt if it come from program argument
                                             // or parent job runtime
          context.sunbird_cassandra_password = pwd_sunbird_cassandra_password_value;
        } else if (!pwd_sunbird_cassandra_password_value.isEmpty()) {
          try {
            context.sunbird_cassandra_password =
                routines.system.PasswordEncryptUtil.decryptPassword(
                    pwd_sunbird_cassandra_password_value);
            context.put("sunbird_cassandra_password", context.sunbird_cassandra_password);
          } catch (java.lang.RuntimeException e) {
            // do nothing
          }
        }
      }
      context.setContextType("sunbird_cassandra_port", "id_String");

      context.sunbird_cassandra_port = (String) context.getProperty("sunbird_cassandra_port");
      context.setContextType("sunbird_cassandra_server", "id_String");

      context.sunbird_cassandra_server = (String) context.getProperty("sunbird_cassandra_server");
      context.setContextType("sunbird_cassandra_username", "id_String");

      context.sunbird_cassandra_username =
          (String) context.getProperty("sunbird_cassandra_username");
      context.setContextType("sunbird_channel_migration_log_file", "id_String");

      context.sunbird_channel_migration_log_file =
          (String) context.getProperty("sunbird_channel_migration_log_file");
    } catch (java.io.IOException ie) {
      System.err.println("Could not load context " + contextStr);
      ie.printStackTrace();
    }

    // get context value from parent directly
    if (parentContextMap != null && !parentContextMap.isEmpty()) {
      if (parentContextMap.containsKey("sunbird_cassandra_keyspace")) {
        context.sunbird_cassandra_keyspace =
            (String) parentContextMap.get("sunbird_cassandra_keyspace");
      }
      if (parentContextMap.containsKey("sunbird_cassandra_password")) {
        context.sunbird_cassandra_password =
            (java.lang.String) parentContextMap.get("sunbird_cassandra_password");
      }
      if (parentContextMap.containsKey("sunbird_cassandra_port")) {
        context.sunbird_cassandra_port = (String) parentContextMap.get("sunbird_cassandra_port");
      }
      if (parentContextMap.containsKey("sunbird_cassandra_server")) {
        context.sunbird_cassandra_server =
            (String) parentContextMap.get("sunbird_cassandra_server");
      }
      if (parentContextMap.containsKey("sunbird_cassandra_username")) {
        context.sunbird_cassandra_username =
            (String) parentContextMap.get("sunbird_cassandra_username");
      }
      if (parentContextMap.containsKey("sunbird_channel_migration_log_file")) {
        context.sunbird_channel_migration_log_file =
            (String) parentContextMap.get("sunbird_channel_migration_log_file");
      }
    }

    // Resume: init the resumeUtil
    resumeEntryMethodName = ResumeUtil.getResumeEntryMethodName(resuming_checkpoint_path);
    resumeUtil = new ResumeUtil(resuming_logs_dir_path, isChildJob, rootPid);
    resumeUtil.initCommonInfo(
        pid, rootPid, fatherPid, projectName, jobName, contextStr, jobVersion);

    List<String> parametersToEncrypt = new java.util.ArrayList<String>();
    parametersToEncrypt.add("sunbird_cassandra_password");
    // Resume: jobStart
    resumeUtil.addLog(
        "JOB_STARTED",
        "JOB:" + jobName,
        parent_part_launcher,
        Thread.currentThread().getId() + "",
        "",
        "",
        "",
        "",
        resumeUtil.convertToJsonText(context, parametersToEncrypt));

    if (execStat) {
      try {
        runStat.openSocket(!isChildJob);
        runStat.setAllPID(rootPid, fatherPid, pid, jobName);
        runStat.startThreadStat(clientHost, portStats);
        runStat.updateStatOnJob(RunStat.JOBSTART, fatherNode);
      } catch (java.io.IOException ioException) {
        ioException.printStackTrace();
      }
    }

    java.util.concurrent.ConcurrentHashMap<Object, Object> concurrentHashMap =
        new java.util.concurrent.ConcurrentHashMap<Object, Object>();
    globalMap.put("concurrentHashMap", concurrentHashMap);

    long startUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
    long endUsedMemory = 0;
    long end = 0;

    startTime = System.currentTimeMillis();

    this.globalResumeTicket = true; // to run tPreJob

    this.globalResumeTicket = false; // to run others jobs

    try {
      errorCode = null;
      tCassandraConnection_1Process(globalMap);
      if (!"failure".equals(status)) {
        status = "end";
      }
    } catch (TalendException e_tCassandraConnection_1) {
      globalMap.put("tCassandraConnection_1_SUBPROCESS_STATE", -1);

      e_tCassandraConnection_1.printStackTrace();
    }

    this.globalResumeTicket = true; // to run tPostJob

    end = System.currentTimeMillis();

    if (watch) {
      System.out.println((end - startTime) + " milliseconds");
    }

    endUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
    if (false) {
      System.out.println(
          (endUsedMemory - startUsedMemory)
              + " bytes memory increase when running : UserMigrationUpdateChannel");
    }

    if (execStat) {
      runStat.updateStatOnJob(RunStat.JOBEND, fatherNode);
      runStat.stopThreadStat();
    }
    int returnCode = 0;
    if (errorCode == null) {
      returnCode = status != null && status.equals("failure") ? 1 : 0;
    } else {
      returnCode = errorCode.intValue();
    }
    resumeUtil.addLog(
        "JOB_ENDED",
        "JOB:" + jobName,
        parent_part_launcher,
        Thread.currentThread().getId() + "",
        "",
        "" + returnCode,
        "",
        "",
        "");

    return returnCode;
  }

  // only for OSGi env
  public void destroy() {
    closeCassandraConnections();
  }

  private void closeCassandraConnections() {
    try {
      Object obj_cluster;
      Object obj_conn;
      obj_cluster = globalMap.remove("cluster_tCassandraConnection_1");
      obj_conn = globalMap.remove("connection_tCassandraConnection_1");
      if (obj_conn != null) {
        ((com.datastax.driver.core.Session) obj_conn).close();
      }
      if (obj_cluster != null) {
        ((com.datastax.driver.core.Cluster) obj_cluster).close();
      }
    } catch (java.lang.Exception e) {
    }
  }

  private java.util.Map<String, Object> getSharedConnections4REST() {
    java.util.Map<String, Object> connections = new java.util.HashMap<String, Object>();
    connections.put(
        "connection_tCassandraConnection_1", globalMap.get("connection_tCassandraConnection_1"));
    connections.put(
        "cluster_tCassandraConnection_1", globalMap.get("cluster_tCassandraConnection_1"));

    return connections;
  }

  private void evalParam(String arg) {
    if (arg.startsWith("--resuming_logs_dir_path")) {
      resuming_logs_dir_path = arg.substring(25);
    } else if (arg.startsWith("--resuming_checkpoint_path")) {
      resuming_checkpoint_path = arg.substring(27);
    } else if (arg.startsWith("--parent_part_launcher")) {
      parent_part_launcher = arg.substring(23);
    } else if (arg.startsWith("--watch")) {
      watch = true;
    } else if (arg.startsWith("--stat_port=")) {
      String portStatsStr = arg.substring(12);
      if (portStatsStr != null && !portStatsStr.equals("null")) {
        portStats = Integer.parseInt(portStatsStr);
      }
    } else if (arg.startsWith("--trace_port=")) {
      portTraces = Integer.parseInt(arg.substring(13));
    } else if (arg.startsWith("--client_host=")) {
      clientHost = arg.substring(14);
    } else if (arg.startsWith("--context=")) {
      contextStr = arg.substring(10);
      isDefaultContext = false;
    } else if (arg.startsWith("--father_pid=")) {
      fatherPid = arg.substring(13);
    } else if (arg.startsWith("--root_pid=")) {
      rootPid = arg.substring(11);
    } else if (arg.startsWith("--father_node=")) {
      fatherNode = arg.substring(14);
    } else if (arg.startsWith("--pid=")) {
      pid = arg.substring(6);
    } else if (arg.startsWith("--context_type")) {
      String keyValue = arg.substring(15);
      int index = -1;
      if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
        if (fatherPid == null) {
          context_param.setContextType(
              keyValue.substring(0, index), replaceEscapeChars(keyValue.substring(index + 1)));
        } else { // the subjob won't escape the especial chars
          context_param.setContextType(keyValue.substring(0, index), keyValue.substring(index + 1));
        }
      }

    } else if (arg.startsWith("--context_param")) {
      String keyValue = arg.substring(16);
      int index = -1;
      if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
        if (fatherPid == null) {
          context_param.put(
              keyValue.substring(0, index), replaceEscapeChars(keyValue.substring(index + 1)));
        } else { // the subjob won't escape the especial chars
          context_param.put(keyValue.substring(0, index), keyValue.substring(index + 1));
        }
      }
    } else if (arg.startsWith("--log4jLevel=")) {
      log4jLevel = arg.substring(13);
    }
  }

  private static final String NULL_VALUE_EXPRESSION_IN_COMMAND_STRING_FOR_CHILD_JOB_ONLY =
      "<TALEND_NULL>";

  private final String[][] escapeChars = {
    {"\\\\", "\\"},
    {"\\n", "\n"},
    {"\\'", "\'"},
    {"\\r", "\r"},
    {"\\f", "\f"},
    {"\\b", "\b"},
    {"\\t", "\t"}
  };

  private String replaceEscapeChars(String keyValue) {

    if (keyValue == null || ("").equals(keyValue.trim())) {
      return keyValue;
    }

    StringBuilder result = new StringBuilder();
    int currIndex = 0;
    while (currIndex < keyValue.length()) {
      int index = -1;
      // judege if the left string includes escape chars
      for (String[] strArray : escapeChars) {
        index = keyValue.indexOf(strArray[0], currIndex);
        if (index >= 0) {

          result.append(
              keyValue
                  .substring(currIndex, index + strArray[0].length())
                  .replace(strArray[0], strArray[1]));
          currIndex = index + strArray[0].length();
          break;
        }
      }
      // if the left string doesn't include escape chars, append the left into the result
      if (index < 0) {
        result.append(keyValue.substring(currIndex));
        currIndex = currIndex + keyValue.length();
      }
    }

    return result.toString();
  }

  public Integer getErrorCode() {
    return errorCode;
  }

  public String getStatus() {
    return status;
  }

  ResumeUtil resumeUtil = null;
}
/**
 * **********************************************************************************************
 * 97244 characters generated by Talend Open Studio for Big Data on the August 26, 2018 3:25:26 PM
 * IST
 * **********************************************************************************************
 */
