version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: lms-dependency-cache-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - save_cache:
          key: lms-dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=project-sunbird_sunbird-utils -Dsonar.organization=project-sunbird -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.jacoco.xmlReportPaths=/home/circleci/project/notification-sdk/target/site/jacoco/jacoco.xml,/home/circleci/project/sunbird-platform-core/common-util/target/site/jacoco/jacoco.xml,/home/circleci/project/sunbird-es-utils/target/site/jacoco/jacoco.xml,/home/circleci/project/sunbird-notification/target/site/jacoco/jacoco.xml,/home/circleci/project/sunbird-cassandra-utils/target/site/jacoco/jacoco.xml
#dummy line
workflows:
  version: 2.1
  workflow:
    jobs:
      - build
